name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 6.x.x

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '16'
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm type-check
      - run: pnpm build
      - run: pnpm type-check:tests
      - run: pnpm test
